---
title: "Extended Data Fig.7,9_scRNAseq of OSKM-mediated reprogramming"
author: "Bum Suk Kim"
date: '2020 12 14 '
output: html_document
---

## Load required libraries and input files.
```{r setup, include=FALSE}
library(Seurat)
library(scater)
library(ggplot2)
library(dplyr)
library(viridis)
library(pheatmap)
library(RColorBrewer)
```


## Load input files
```{r cars}
dIC_seurat3 = readRDS("dIC_seurat3_whole.rds")
load("ensemblGenes 20180625 .RData")
wot_sig <- read.csv("signiture_gene.csv") Schiebinger et al. 2019
```

## Set condition leve & color
```{r cars}
dIC_seurat3@meta.data$condition = factor(dIC_seurat3@meta.data$condition,
                                           levels =  c("MEF", "D2", "D4", "D5", "D6_iNSC" , "D7_iNSC",  "D8_iNSC",  "D10_iNSC",  
                                                       "iNSC",  "D6_iPSC", "D7_iPSC", "D8_iPSC", "D10_iPSC", "iPSC"))       


myColors_Whole <- c("red",                  #MEF
                    "orangered",            #D2
                    "indianred",            #D4
                    "hotpink",              #D5
                    "#2196F3" ,             #D6_iNSC
                    "#3F51B5",              #D7_iNSC
                    "lightslateblue",       #D8_iNSC
                    "purple3",              #D10_iNSC
                    "blue",                 #iNSC
                    "orange",               #D6_iPSC
                    "yellow2",              #D7_iPSC
                    "yellowgreen",          #D8_iPSC
                    "mediumspringgreen",    #D10_iPSC
                    "springgreen4")         #iPSC
```



## Plot signature score
```{r pressure, echo=FALSE}


rownames(dIC_seurat3@assays$RNA@data) = uniquifyFeatureNames(ID = rownames(dIC_seurat3@assays$RNA@data),
names = ensemblGenes$external_gene_name[match(rownames(dIC_seurat3@assays$RNA@data),
ensemblGenes$ensembl_gene_id)])

cnt_norm = as.matrix(dIC_seurat3@assays$RNA@data)
mat_z = t(scale(t(cnt_norm)))
mat_z = mat_z[!is.na(rowSums(mat_z)),]

for (signature in c("MEF.identity", "Pluripotency", "Neural.identity")) {
  geneset = as.character(wot_sig[,signature])
  all_z = data.frame(means=colMeans(mat_z[rownames(mat_z) %in% geneset,]))
  
  df = data.frame(x=DIC_seurat3_sub@reductions$umap@cell.embeddings[,1], 
                  y=DIC_seurat3_sub@reductions$umap@cell.embeddings[,2],
                  expression=all_z[,1]) 
    df = df[order(df$expression),]
    p=ggplot(df,aes(x=x, y=y, colour=expression)) +
      geom_point(size=1) +
      scale_color_viridis(option = "D",
                          # limits = c(-1, 1),
                          guide = guide_colourbar(ticks = F, barheight = 15, barwidth = 2))+
      theme_bw() +
      theme(plot.title = element_text(size = 20, face = "italic", hjust = 0.5),
            axis.line=element_blank(),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            axis.ticks=element_blank(),
            axis.title.x=element_blank(),
            axis.title.y=element_blank(),
            panel.background=element_blank(),
            panel.border=element_blank(),
            panel.grid.major=element_blank(),
            panel.grid.minor=element_blank(),
            plot.background=element_blank(),
            legend.text=element_text(size=17),
            legend.title = element_blank()
      )
    ggsave(paste0("figure_umap_", genename,".png"), p, width = 7, height = 7)
    }

```


## Plot heatmap
```{r pressure, echo=FALSE}

genes = c("Pou5f1", "Nanog", "Zfp42", "Esrrb", "Dppa4", "Dppa5a", "Sall4", "Sox2")
genes_mat = as.matrix(dIC_seurat3@assays$RNA@data[ensemblGenes$ensembl_gene_id[ensemblGenes$external_gene_name %in% genes], ])
rownames(genes_mat) = ensemblGenes$external_gene_name[match(rownames(genes_mat), ensemblGenes$ensembl_gene_id, nomatch = 0)]
genes_mat = genes_mat[genes, ]


############### iPSC route
condition = c("D2", "D4", "D5", "D6_iPSC", "D7_iPSC", "D8_iPSC", "D10_iPSC", "iPSC")

count_sorted<- data.frame(rowMeans(genes_mat[,dIC_seurat3$condition == "MEF"]))
for(i in condition){
  count_sorted <- cbind(count_sorted, data.frame(rowMeans(genes_mat[,dIC_seurat3$condition==i])))
}
colnames(count_sorted) = c("MEF", condition)

count_sorted<- genes_mat[,dIC_seurat3$condition == "MEF"]
for(i in condition){
  count_sorted <- cbind(count_sorted, genes_mat[,dIC_seurat3$condition==i])
}

cl_t<-table(dIC_seurat3$condition)
x<-c()
for(i in c("MEF", condition)){
  x <- append(x,rep(i,cl_t[[i]]))
}
df= data.frame(
  condition=factor(x)
)
#### if rowname is unmached, color don't come up
rownames(df)<-colnames(count_sorted)

cour<-list(
  condition=c("MEF"=myColors_Whole[1],
              "D2"=myColors_Whole[2],
              "D4"=myColors_Whole[3],
              "D5"=myColors_Whole[4],
              "D6_iPSC"=myColors_Whole[10],
              "D7_iPSC"=myColors_Whole[11],
              "D8_iPSC"=myColors_Whole[12],
              "D10_iPSC"=myColors_Whole[13],
              "iPSC"=myColors_Whole[14]
  )
)

count_sorted_z = t(scale(t(count_sorted)))
count_sorted_z[count_sorted_z>3] = 3
count_sorted_z[count_sorted_z<  -3] = -3


res = pheatmap(count_sorted_z,
               show_rownames = T,
               show_colnames = F,
               annotation_col = df,
               annotation_names_col = F,
               annotation_colors = cour,
               cluster_cols = F,
               cluster_rows = F,
               annotation_legend = T,
               fontsize = 10,
               color = colorRampPalette(rev(brewer.pal(n = 7, name ="RdBu")))(100)
)

pdf("Heatmap_markers_iPSC.pdf")
res
dev.off()



############### iNSC route
condition = c("D2", "D4", "D5", "D6_iNSC", "D7_iNSC", "D8_iNSC", "D10_iNSC", "iNSC")

count_sorted<- data.frame(rowMeans(genes_mat[,dIC_seurat3$condition == "MEF"]))
for(i in condition){
  count_sorted <- cbind(count_sorted, data.frame(rowMeans(genes_mat[,dIC_seurat3$condition==i])))
}
colnames(count_sorted) = c("MEF", condition)

count_sorted<- genes_mat[,dIC_seurat3$condition == "MEF"]
for(i in condition){
  count_sorted <- cbind(count_sorted, genes_mat[,dIC_seurat3$condition==i])
}

cl_t<-table(dIC_seurat3$condition)
x<-c()
for(i in c("MEF", condition)){
  x <- append(x,rep(i,cl_t[[i]]))
}
df= data.frame(
  condition=factor(x)
)
#### if rowname is unmached, color don't come up
rownames(df)<-colnames(count_sorted)

cour<-list(
  condition=c("MEF"=myColors_Whole[1],
              "D2"=myColors_Whole[2],
              "D4"=myColors_Whole[3],
              "D5"=myColors_Whole[4],
              "D6_iNSC"=myColors_Whole[5],
              "D7_iNSC"=myColors_Whole[6],
              "D8_iNSC"=myColors_Whole[7],
              "D10_iNSC"=myColors_Whole[8],
              "iNSC"=myColors_Whole[9]
  )
)

count_sorted_z = t(scale(t(count_sorted)))
count_sorted_z[count_sorted_z>3] = 3
count_sorted_z[count_sorted_z<  -3] = -3
library(pheatmap)
library(RColorBrewer)
res = pheatmap(count_sorted_z,
               show_rownames = T,
               show_colnames = F,
               annotation_col = df,
               annotation_names_col = F,
               annotation_colors = cour,
               cluster_cols = F,
               cluster_rows = F,
               annotation_legend = T,
               fontsize = 10,
               color = colorRampPalette(rev(brewer.pal(n = 7, name ="RdBu")))(100)
)

pdf("Heatmap_markers_iPSC.pdf")
res
dev.off()

```
